apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-creator-demo
  namespace: default
  labels:
    app: pod-creator-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-creator-demo
  template:
    metadata:
      labels:
        app: pod-creator-demo
    spec:
      nodeSelector:
        lts: lts
      serviceAccountName: pod-creator-sa
      containers:
        - name: pod-creator-demo
          image: containercloud-mirror.xaidc.com/containercloud/pod-creator:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 22
              name: ssh

---
apiVersion: v1
kind: Service
metadata:
  name: pod-creator-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: pod-creator-demo
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31231
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 31232