apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-creator-demo
  namespace: default
  labels:
    app: pod-creator-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-creator-demo
  template:
    metadata:
      labels:
        app: pod-creator-demo
    spec:
      nodeSelector:
        lts: lts
      serviceAccountName: pod-creator-sa
      initContainers:
        - name: generate-ssh-password
          image: containercloud-mirror.xaidc.com/library/alpine:3.2.0
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              PASSWORD=$(openssl rand -base64 12)
              echo "${PASSWORD}" > /home/ssh/ssh-password
              echo "SSH PASSWORD: ${PASSWORD}"
          volumeMounts:
            - name: ssh-password-volume
              mountPath: /home/ssh
      containers:
        - name: pod-creator-demo
          image: containercloud-mirror.xaidc.com/containercloud/pod-creator:v1
          imagePullPolicy: Always
          volumeMounts:
            - name: ssh-password-volume
              mountPath: /home/ssh
              readOnly: true
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 22
              name: ssh
      volumes:
        - name: ssh-password-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: pod-creator-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: pod-creator-demo
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 31231
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 31232